export const CASES_FETCH = "CASES_FETCH";
export const CASES_FETCH_SUCCESS = "CASES_FETCH_SUCCESS";
export const CASES_FETCH_START = "CASES_FETCH_START";
export const CASES_FETCH_FAIL = "CASES_FETCH_FAIL";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_PAGE_SIZE = "UPDATE_PAGE_SIZE";




